Repository nanoframework/nf-debugger, pull requests merged in 2019-03, with the labels that each got.

#185 Fix update network config
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: bug

#186 Improve disconnection of SerialDevice
  source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
Labels: Type: enhancement

#187 Fix getting configuration blocks
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  source/nanoFramework.Tools.Debugger.sln
Labels: Type: bug

#188 Add output to help debug device state
  source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
Labels: Type: enhancement

#189 Work on DeploymentExecuteIncremental
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: enhancement

#190 Add output of error codes on WriteMemory
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: enhancement

#191 Add new method UpdateDebugFlags
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Breaking-Change, Type: enhancement

#192 Fix progress output on DeploymentExecuteIncremental
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: bug

#193 Improve code on EraseAsync
  source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
Labels: Type: bug

#194 Improvements in EraseAsync
  source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
Labels: Breaking-Change, Type: enhancement
