Repository nanoframework/nf-debugger, pull requests merged in 2019-07, with the labels that each got.

#203 Fix deployment progress message
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: bug

#204 Update serial baud rate to 921600
  source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs
  source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
  source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs
  source/version.json
Labels: Breaking-Change, CI: Publish Release

#205 Improvements in deployment
  source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: enhancement

#206 Fix OemInfo command
  source/USB Test App WPF/MainWindow.xaml
  source/USB Test App WPF/MainWindow.xaml.cs
  source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  source/version.json
Labels: Type: bug

#207 Replace chars in ToString output on device capabilities
  source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
Labels: Type: enhancement
