Repository nanoframework/nf-debugger, pull requests merged in 2021-09, with the labels that each got.

#319 Add UNIX support for PortSerial
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Labels: Type: enhancement

#320 Improved Linux SerialPort lookup
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Labels: Type: bug, Type: enhancement

#321 Add timeout to PerformSyncRequest
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: Type: enhancement

#318 TCP/IP debugger port implementation
  USB Test App WPF/App.xaml.cs
  nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs
  nanoFramework.Tools.DebugLibrary.Net/PortTcpIp/PortTcpIp.cs
  nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/NanoNetworkDevice.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/NetworkNanoDeviceInformation.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/NetworkWatcher.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/PortTcpIp.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/PortTcpIpDeviceManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
Labels: Type: enhancement, CI: Update Dependents
