Repository nanoframework/nf-debugger, pull requests merged in 2021-05, with the labels that each got.

#302 Fix initialization of Expires in WP Request
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
Labels: CI: Update Dependents, Type: bug

#303 Improving device watcher
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Labels: CI: Update Dependents, Type: bug

#304 Work on serial device detection
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: CI: Update Dependents, Type: enhancement

#306 Improvements in serial comms
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: CI: Update Dependents, Type: enhancement

#307 Improvements in port connection
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/INanoDevice.cs
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs
  nanoFramework.Tools.DebugLibrary.Shared/NanoDevicesEventSource.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/IPort.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ConnectPortResult.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IController.cs
  nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
Labels: Type: enhancement

#308 Improve WP request send
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IController.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHost.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
Labels: CI: Update Dependents, Type: enhancement

#309 Improvements in device detection
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
Labels: Type: enhancement

#311 Fix set execution
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
Labels: Type: bug

#312 Reboot now returns operation result
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: CI: Update Dependents, Type: enhancement

#313 General improvements
  nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Labels: CI: Update Dependents, Type: enhancement
