Repository nanoframework/nf-debugger, pull requests merged in 2023-04, with the labels that each got.

#358 Revert DataAnnotations to v6.0
  nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
Labels: Type: dependencies, CI: Update Dependents

#359 Update DataAnnotations NuGet
  nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
Labels: Type: dependencies, CI: Update Dependents

#361 Add AddDevice method to PortBase
  nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/PortTcpIpManager.cs
Labels: Type: enhancement, CI: Update Dependents

#362 Add new constructors to PortBase
  nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs
Labels: Type: enhancement

#363 Intellisense comments
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
Labels: Type: documentation

#360 Fixing serial read on M1 and when only partial data is available
  nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
Labels: Type: bug, CI: Update Dependents
